baseurl = "https://www.johnwilson.co/"
languageCode = "en-us"
title = "John Wilson"
theme = "hugo-strata-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-10176160-4"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "John Wilson"
	description = "Portfolio"

	# Format dates with Go's time formatting
	date_format = "2006-02-28"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm John**, analytics and strategy expert. <br> Author of the blog [Joygret](//medium.com/joygret)."
		# The icons will be shown if you enter your username
		twitter = "johnawilsontn"
		github = "armistead"
		#gitlab = "spf13"
		#dribbble = ""
		#facebook = ""
		#googleplus = ""
		#flickr = ""
		linkedin = "johnawilson"

		copyright = [
			"&copy; John Wilson",
			"Design: [HTML5 UP](//html5up.net)",
			"Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Welcome home."
		content = "This is my portfolio of recent work."


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.png"
			thumb = "thumbs/01.png"
			title = "Tableau"
			description = "Tool for finding and filtering for vegan/vegetarian restaurants across the US.
			[Click here to view public dashboard.] (https://public.tableau.com/profile/armistead#!/vizhome/VeganVegetarianRestaurantsintheUS/Dashboard)"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "R"
			description = "One of the assignments I completed for the Data Science Coursera on R."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

#		[[params.portfolio.gallery]]
#			image = "fulls/05.jpg"
#			thumb = "thumbs/05.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."

#		[[params.portfolio.gallery]]
#			image = "fulls/06.jpg"
#			thumb = "thumbs/06.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "I am available for project based work or part-time consulting."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "36.1818226,-86.7942848"
		address = [
			"PO Box 282462",
			"Nashville, TN 37228",
			"USA"
		]
#		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "me@johnwilson.co"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
